### PR TITLE
Update README

### PR DESCRIPTION
**Pull request by justinsimonelli**
Updating README with the available options. Hopefully add all the option configs as well in the future

### CODE REVIEW

**Comment by Stahl80** [comment]
Nice! It's COVID an item also?

**Comment by justinsimonelli** [comment]
> Nice! Isn't COVID an item also?

Good catch, added!

**Comment by mzeryck** [comment]
@justinsimonelli Hi Justin, thanks for the pull request! I'd prefer not to duplicate the item list, since they're all also listed in prose right above the section you added. I do think listing them out vertically is easier to read - would you mind reformatting the paragraph before so it's not repetitive? Thanks!

**Comment by TheRealEvan584** [comment]
Now you also need to add the “week” element to the README. Additionally the COVID and WEEK elements are missing from weather-cal.js when all of the possible elements are listed.

**Comment by justinsimonelli** [comment]
@mzeryck oh shoot I didn’t see those. I’ll update the paragraph, thanks!

**Comment by justinsimonelli** [comment]
@mzeryck fixed, let me know what you think.
@TheRealEvan584 added!

**Comment by mzeryck** [comment]
@justinsimonelli Great, thank you!

**Pull request merged**
